title: WCCA Robotics
description: "Robotics teams of West Coast Christian Academy — competing in FIRST Tech Challenge and FIRST LEGO League"
url: "https://wccarobotics.org"
baseurl: ""

markdown: kramdown
plugins: []

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

collections_dir: .

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "tournaments"
    values:
      team_highlight: true
  - scope:
      path: "scouting"
    values:
      team_highlight: true
